// A local source-review packet. No network requests and no invented human reviews.
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {auditDataset} from '../api/src/evidence.js';
const [inputPath,out]=process.argv.slice(2);
if(!inputPath||!out)throw Error('Usage: node scripts/evidence_workbench.mjs INPUT.json OUTPUT_DIRECTORY');
const input=JSON.parse(readFileSync(inputPath)),data=auditDataset(input);
if(data.audit.error)throw Error(data.audit.error);
mkdirSync(out,{recursive:true});
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cards=[...data.incidents,...data.context].map(r=>`<article><h2>${escape(r.location.label||r.id)}</h2><p>${escape(r.summary)}</p><p>${escape(r.occurred.label)} · ${escape(r.setting)} · ${escape(r.report_status)}</p><p><strong>${r.eligible?'Street admission criteria met':'Context only'}</strong>: ${escape(r.exclusion_reason||r.location.reason)}</p><p>Source checks: ${r.source_review_count}. Location checks: ${r.review_count}. This is declared review metadata, not authenticated independent validation.</p><p>${r.references.map(ref=>`<a href="${escape(ref.url)}" rel="noreferrer">${escape(ref.source)}</a>`).join(' · ')}</p><code>${escape(r.id)}</code></article>`).join('');
writeFileSync(join(out,'review.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Salt Lake evidence review</title><style>body{font:16px system-ui;background:#f5f4fa;color:#211b32;max-width:850px;margin:24px auto;padding:0 20px;line-height:1.5}article{background:white;padding:20px;margin:16px 0;border:1px solid #ddd;border-radius:12px}a{overflow-wrap:anywhere;color:#493095}code{overflow-wrap:anywhere}</style><h1>Salt Lake evidence review</h1><p>Dataset ${escape(input.version)}. ${data.incidents.length} admitted street events; ${data.context.length} context records. Accuracy is unmeasured.</p><p>Check the original source, event date, public-space setting, actual incident site (rather than arrest, residence or complaint station), aliases, parallel roads, bridges, walls, side of the street and independent reviewer identities. Retain unresolved locations. No field visit is required if an authorized provider supplies sufficiently precise dated records; map inspection alone cannot establish lighting conditions.</p>${cards}<p>See review-template.json. Complete it using real reviewers, then merge reviews into a new version of the source dataset and rerun the audit. Never replace the automated source checks with invented human identities.</p></html>`,{mode:0o600});
writeFileSync(join(out,'review-template.json'),JSON.stringify({dataset_version:input.version,independent_validation:false,
  instructions:'Each reviewer independently checks the source and location. Use a steward identity, not a name/email. Fill no coordinates until supported by the source and an attributable street geometry. Merge only completed real reviews; this empty template does not pass admission.',
  records:[...data.incidents,...data.context].map(r=>({event_id:r.id,proposed_location:null,reviews:[],questions:['What exactly happened on which date interval?','Is this the incident location and a public walking street?','Which referenced road geometry and name identify it?','Can parallel paths, bridges, walls, sides or conflicting sources change attribution?','Was this separately checked by a second real reviewer?']}))},null,2)+'\n',{mode:0o600});
console.log(JSON.stringify({directory:resolve(out),street_events:data.incidents.length,context_records:data.context.length,accuracy:'UNMEASURED'}));
